### ISSUE TITLE
Error: InvalidOperation: (:) [], RuntimeException

### ISSUE THREAD

**Issue by milewski** [aaronsace/MultiPoolMiner#613]
I keep getting this error every time.... it seems to be working fine trough... but this message pops up every minute or so... 

```
WARNING: Pool API (Hashrefinery) has failed.
WARNING: Pool API (MiningPoolHub) has failed.
You cannot call a method on a null-valued expression.
At C:\Users\Rafael\Desktop\MultiPoolMinerV2.7.0.2\Pools\MiningPoolHub.ps1:17 char:5
+     $MiningPoolHub_Hosts = $_.all_host_list.split(";")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WARNING: Pool API (NiceHash) has failed.
```

**Comment by aaronsace** [comment]
I forgot to hide the error in the release; it causes no issues. Was only when NiceHash went down that it became annoying. It's fixed in the master code branch.

**Comment by dnxtgn** [comment]
It seems this issue is still there:

Keep getting below error and miner doesn't work


Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Users\AB-PC\Desktop\Mine\MultiPoolMinerV2.7.1.1\MultiPoolMiner.ps1:123 char:17
+ ... $NewRates = Invoke-RestMethod "https://api.coinbase.com/v2/exchange-r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

WARNING: Pool API (MiningPoolHub) has failed.
WARNING: Pool API (MiningPoolHubCoins) has failed.
WARNING: No pools available.
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Users\AB-PC\Desktop\Mine\MultiPoolMinerV2.7.1.1\MultiPoolMiner.ps1:123 char:17
+ ... $NewRates = Invoke-RestMethod "https://api.coinbase.com/v2/exchange-r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

WARNING: Pool API (MiningPoolHub) has failed.
WARNING: Pool API (MiningPoolHubCoins) has failed.
WARNING: No pools available.
WARNING: MultiPoolMiner is out of date; there is an updated version available at https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.1.1/MultiPoolMinerV2.7.1.1.zip.

Although I am using version 2.7.1.1 the same error keeps poping up and doesn't work :(
